name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: test
      run: |
        echo "${{ github.event_name}}"
    - name: Assign NEW issues to column to do
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      with:
        project: 'https://github.com/ibakshay/project-board/projects/1'
  #   - name: echo 
    #   run: |
      #  echo "${{ github.event_name}}"

    - name: Assign NEW pull requests to column review
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event_name == 'pull_request' && github.event == 'opened'
      with:
        project: 'https://github.com/ibakshay/project-board/projects/1'
        column_name: 'review'
